//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleCalculator.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        public static string DivideOperation {
            get {
                return ResourceManager.GetString("DivideOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the first operand.
        /// </summary>
        public static string FirstOperand {
            get {
                return ResourceManager.GetString("FirstOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You couln&apos;t devide by zero.
        /// </summary>
        public static string InvalidDivision {
            get {
                return ResourceManager.GetString("InvalidDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        public static string MultiplyOperation {
            get {
                return ResourceManager.GetString("MultiplyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick a color.
        /// </summary>
        public static string PickAColor {
            get {
                return ResourceManager.GetString("PickAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result is.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the second operand.
        /// </summary>
        public static string SecondOperand {
            get {
                return ResourceManager.GetString("SecondOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        public static string SubtractOperation {
            get {
                return ResourceManager.GetString("SubtractOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string SumOperation {
            get {
                return ResourceManager.GetString("SumOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the operation you want to execute.
        /// </summary>
        public static string TypeOfOperation {
            get {
                return ResourceManager.GetString("TypeOfOperation", resourceCulture);
            }
        }
    }
}
